modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId="aeroclaims_ftb"
version="1.0.0"
displayName="Aeronautics Claims"
authors="Mapter"
description='''
Aeronautics Claims.
'''

[[mixins]]
config = "aeroclaims_ftb.mixins.json"

[[dependencies.aeroclaims_ftb]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.200,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aeroclaims_ftb]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aeroclaims_ftb]]
modId = "ftbchunks"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.aeroclaims_ftb]]
modId = "ftbteams"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
